### PR TITLE
Updated to 0.264.0

### PR DESCRIPTION
**Pull request by aviflombaum**

### CODE REVIEW

**Comment by heyvito** [comment]
Hey @aviflombaum! Thanks for contributing! Did something went wrong? :(

**Comment by aviflombaum** [comment]
Ya, it broke the build. I had run the command to update the icons to the latest version thinking it would just work but then got an error about passing too many arguments into lucide_icon. I didn't have time to take a look but didn't want broken code to get merged. I'll look today.

**Comment by heyvito** [comment]
ahhh, I see! Let me know in case you need a helping hand! 🙌🏻

**Comment by aviflombaum** [comment]
Hey - ya, just discovered that, missed this comment. I tried a bunch of things but the best I came up with is:

```ruby
      @memory = data.split("\x00").each_with_object({}) do |element, result|
        key, value = element.match(/^([^,]*),(.*)$/).captures
        result[key] = value
      end
```

or 

```ruby
      @memory = data.split("\x00").each_with_object({}) do |element, result|
        key, *value_parts = element.split(",")
        value = value_parts.join(",")
        result[key] = value
      end
```

I can push whichever you think is more elegant but if you find an easier way, go for it, please.

**Comment by heyvito** [comment]
@aviflombaum Fixed by https://github.com/heyvito/lucide-rails/commit/0b50525b722fbe72f2144ba68a20e149c0780875#diff-801eb78c3d10048c0033c094aebe7498b512135d55fa1015a7d1b40939405da8R30 ✨ 

Feel free to reopen this PR or create a new one! I'm also merging some dependabot PRs, so don't forget to update your fork! 🙌🏻

**Comment by heyvito** [comment]
Just finished merging security updates! I'll make sure to merge this one before next ones!

**Comment by aviflombaum** [comment]
Sorry, was trying to figure out if I needed to push the updates from upstream to this PR but I don't.

**Comment by heyvito** [comment]
I think GitHub now has a "sync" button on your fork page that allows changes to be fetched automagically... I'm not sure whether it would work due to that conflict, tho.

If it is unable to correctly sync, you can amend [eaeb0f9](https://github.com/heyvito/lucide-rails/pull/7/commits/eaeb0f90998486810be17f014bfac145aa41a781) and drop changes to that lock file, force-push, and then try the sync. Let me know in case you need help with that and I can provide specific steps 🙌🏻

**Comment by heyvito** [comment]
Oh! Just forgot about the "Maintainers can edit this PR" feature as well! I can try to fix that conflict for you if you'd like! It's ezpz! :)
Let me know and I can try to give it a whirl.

(I apologise for the multiple messages!)

**Comment by heyvito** [comment]
Superseded by #11

**Pull request closed without merging**
